timebound/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (
		password_reset, 
   		password_reset_done,
  		password_reset_confirm,
   		password_reset_complete
	)
from django.conf import settings
from django.conf.urls.static import static
from mythbala import views

app_name = 'mythbala'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<week_number>[0-9]+)/$', 
			views.week_detail, 
			name='week_detail'
		),
	url(r'^(?P<week_number>[0-9]+)/(?P<thing_name>[\w-]+)/$', 
			views.thing_detail, 
			name='thing_detail',
		),
	
	url(r'^accounts/password/reset/$', 
        password_reset,
        {'template_name':
        'registration/password_reset_form.html'},
        name="password_reset"),
    url(r'^accounts/password/reset/done/$',
        password_reset_done,
        {'template_name':
        'registration/password_reset_done.html'},
        name="password_reset_done"),
    url(r'^accounts/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        password_reset_confirm,
        {'template_name':
        'registration/password_reset_confirm.html'},
        name="password_reset_confirm"),
    url(r'^accounts/password/done/$', 
        password_reset_complete,
        {'template_name':
        'registration/password_reset_complete.html'},
        name="password_reset_complete"),

	url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mythbala/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Profile(models.Model):
	name = models.CharField(max_length=25)
	user = models.OneToOneField(User, blank=True, null=True)

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Week(models.Model):
	week_number = models.IntegerField(default=0)
	parent_profile = models.ManyToManyField("Profile")

	def __str__(self):
		return '%s' %(self.week_number)

@python_2_unicode_compatible
class Thing(models.Model):
	parent_week = models.ManyToManyField ("Week")
	#models.OneToOneField(Week,on_delete=models.CASCADE,primary_key=False,)
	thing_name = models.CharField(max_length=25)
	thing_cost = models.IntegerField(default=0)
	#number_available = models.IntegerField(default=0)
	availability = models.BooleanField(default=True)
	photo = models.ImageField(upload_to='mythbala/', null=True)

	def __str__(self):
		return self.thing_name

mythbala/views.py
from django.shortcuts import get_object_or_404, render

from .models import Week, Thing


# Create your views here.
def index(request):
	# in the future, add possibility to view current time here?
	weeks = Week.objects.all()
	context = {
		'weeks' : weeks
	}
	return render(request, 'mythbala/index.html', context)

def week_detail(request, week_number):
	week = get_object_or_404(Week, pk=week_number)
	return render(request, 'mythbala/week_detail.html',
		{'week': week})

def thing_detail(request, week_number, thing_name):
	thing = get_object_or_404(Thing, pk=thing_name)
	return render(request, 'mythbala/thing_detail.html',
		{'thing': thing,
		'week_number': week_number})

mythbala/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
	<title>
		{% block title %}
			Timebound - In Action
		{% endblock title %}
	</title>
	{% block header %} {% endblock header %}
</head>
<body>
	<header>
            <h1>TimeBound - In Action</h1>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'index' %}">Home</a>
                    </li>
                  	{% if user.is_authenticated %}
					<li>
					    <a href="{% url 'auth_logout' %}">Logout</a>
					</li>
					{% else %}
					<li>
					    <a href="{% url 'auth_login' %}">Login</a>
					</li>
					<li>
					    <a href="{% url 'registration_register' %}">Register</a>
					</li>
					{% endif %}
                </ul>
            </nav>
        </header>
{% block content %} {% endblock content %}
{% block footer %} {% endblock footer %}
</body>
</html>

mythbala/templates/mythbala/index.html
{% extends 'base.html' %}

{% block title %}
	Homepage - {{ block.super }}
{% endblock title %}

{% block content %}
	<h2>Weeks</h2>
	{% if weeks %}
	<ul>
		{% for week in weeks %}
			<li>
				<a href="{{ week.week_number }}/"> {{ week.week_number }}</a>
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>Nothing to show here.</p>
	{% endif %}

{% endblock content %}

mythbala/templates/mythbala/thing_detail.html
{% extends "base.html" %}

{% block title %}
	{{ thing.thing_name }} Details - {{ block.super }}
{% endblock title %}

{% block content %}
	<h2> {{ thing.thing_name }} Details </h2>
	<p>This instance of {{ thing.thing_name }} belongs to Week {{ thing.parent_week }}. </p>

	<!-- {% load static %}
	<img src="{% static "mythbala/{{ thing.image_name }}.jpg" %}" alt = {{ thing.image_name }} /> -->

	{% if availability %}
	<p> To buy, you need {{ thing.thing_cost }} seconds in your wallet. </p>
	<!-- add code to buy --> 
	{% else %}
	<p> You've already purchased this thing! </p>
	{% endif %}
{% endblock content %}

mythbala/templates/mythbala/week_detail.html
{% extends "base.html" %}

{% block title %}
	Week {{ week.week_number }} Details - {{ block.super }}
{% endblock title %}

{% block content %}
	<h2> Week {{ week.week_number }} Details </h2>
	<ul>
	{% if week.thing_set.all %}
		{% for things in week.thing_set.all %}
		<li> 
			<a href="{{ things.thing_name }}/"> {{ things.thing_name }} </a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p>Nothing inside!</p>
	{% endif %}
{% endblock content %}